version: '3.8'

services:
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis-data:/data
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"